apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  labels:
    app: consumer-deployment
spec:
  replicas: 0
  selector:
    matchLabels:
      app: consumer-deployment
  template:
    metadata:
      labels:
        app: consumer-deployment
    spec:
      containers:
      - name: consumer
        image: ihorkpi/consumer:1
        env:
        - name: RABBIT_MQ_HOST
          value: rabbitmq
        - name: RABBITMQ_USER
          value: rmuser
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: mq-password
              key: password
        - name: QUEUE_NAME
          value: meassages
